
name: 'academy_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  academy_dbt:
    staging:
      +materialized: table
      +schema: staging

    marts_local:
      materialized: table
      +schema: marts_local
      +tags: conformed
      
    marts_analytics:
      materialized: table
      +schema: marts_analytics
      +tags: conformed
      sales:
        sales_facts:
          sales_facts_sap_adw:
            +tags: sap_adw


seeds:
  academy_dbt:
    +schema: stg