version: 2

sources:
  - name: sap_adw
    description: Banco de dados do SAP AdventureWorks para a execução do desafio de Analytics Egineer da Indicium Academy.
    schema: sap_adw
    tables:      
      # Tabelas que serão utilizadas para compor a dimensão de endereço
      - name: address
        description: Tabela de endereço.
        columns:
          - name: addressid
            description: Chave primária da tabela.
            tests:
              - unique
              - not_null
          - name: stateprovinceid
            description: Chave estrangeira da tabela `stateprovince`.
          - name: city
            description: Nome da cidade.
          - name: modifieddate
            description: Data para partição da tabela.