version: 2

sources:
  - name: raw_staging
    description: Tabelas conformadas.
    schema: raw_staging
    tables:      
      # Tabelas de calendário
      - name: stg_conformed_date
        description: Tabela dimensão de datas.
        columns:
          - name: date_id
            description: Chave primária da tabela.
            tests:
              - unique
              - not_null